spring:
  application:
    name: light-novel-web-api
  datasource:
    url: jdbc:mysql://localhost:3306/ligth_novel_web_db
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EM_USERNAME}
    password: ${EM_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

server:
  port: 8080
jwt:
  signer_key: ${JWT_SIGNER_KEY}
redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}